# Exception
* try-catch-finally 구문도 하나의 값처럼 사용 가능. 변수에 할당하거나 반환값으로 사용
```kotlin
return try {
   str.toInt()
} catch(e: NumberFormatException) {
    null
}
```

* kotlin 에선 CheckedException, UnCheckedException 구분하지 않고, 모두 UnCheckedException 으로 인식.
```kotlin
//AS-IS
try {
File file = new File("/path");
} catch(IoException e) {
    ...
}

//TO-BE
File file = new File("/path");
```

* try-with-resources(A) 구문이 A.use 로 대체됨
```kotlin
//AS-IS
try (BufferedReader reader = new BufferedReader(new FileReader(path))) {
    ...
}
//TO-BE
BufferedReader(FileReader(path)).use {
    ...
}
```